import { Task } from "../../dist/types/public-types";

export function initTasks() {
  const currentDate = new Date();

  const tasks: Task[] = [
    {
      start: new Date(2015, 9, 12),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: "İpotek Teminatları",
      id: "ipotekTeminatları",
      progress: 100,
      type: "project",
      styles: {hide:true},
      hideChildren: false,
      displayOrder: 1,
    },
    {
      start: new Date(2015, 1, 1),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: "#2435644 Teminat Tutarı 1.200.000 TL",
      id: "2435644-ipoTmnt",
      progress: 100,
      type: "task",
      project: "ipotekTeminatları",
      displayOrder: 2,
    },
    {
      start: new Date(2015, 9, 24),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: "İpotek",
      id: "ipotek",
      progress: 100,
      styles: {hide:true},

      type: "project",
      hideChildren: false,
      displayOrder: 3,
    },
    {
      start: new Date(2015, 9, 24),
      end: new Date(2020, 10, 28),
      name: "T. HALK BANKASI A.Ş. İpotek Tutarı 1.200.000 TL 1. Derece Müşteri: ADEM GENÇ",
      id: "ipotek-1",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      styles: { progressColor: 'gray', progressSelectedColor: 'gray',backgroundColor: 'gray' },
      project: "ipotek",
      displayOrder: 4,
    },
    {
      start: new Date(2021, 3, 18),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: " T. HALK BANKASI A.Ş. E-İpotek Tutarı 2.500.000 TL 1. Derece Müşteri: CEMİL MERKANT",
      id: "ipotek-2",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "ipotek",
      displayOrder: 5,
    },
    {
      start: new Date(2021, 7, 22),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: " YAPI VE KREDİ BANKASI A.Ş. İpotek Tutarı 1.800.000 TL 2. Derece Malik: CEMİL MERKANT ",
      id: "ipotek-3",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "ipotek",
      displayOrder: 6,
    },
    {
      start: new Date(2021, 8, 14),
      end: new Date(2022,10,22),
      name: " ING BANK A.Ş. İpotek Tutarı 2.200.000 TL 3. Derece Malik: CEMİL MERKANT  ",
      id: "ipotek-4",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "ipotek",
      styles: { progressColor: 'gray', progressSelectedColor: 'gray',backgroundColor: 'gray' },
      displayOrder: 7,
    },
    {
      start: new Date(2022, 11, 4),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: " QNB FİNANSBANK A.Ş.  İpotek Tutarı 1.100.000 TL 4. Derece Malik: CEMİL MERKANT   ",
      id: "ipotek-5",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "ipotek",
      displayOrder: 8,
    },
    {
      start: new Date(2015, 9, 12),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: "Değerleme Raporları",
      id: "ekspertiz",
      progress: 100,
      type: "project",
      styles: {hide:true},

      hideChildren: false,
      displayOrder: 9,
    },
    {
      start: new Date(2015, 9, 12),
      end: new Date(2017,9,11),
      name: " #2435644 (YD 1.200.000 TL - MD 1.200.000 TL) 1 Konut   ",
      id: "ekspertiz-1",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      styles: { progressColor: 'gray', progressSelectedColor: 'gray',backgroundColor: 'gray' },
      project: "ekspertiz",
      displayOrder: 10,
    },
    {
      start: new Date(2019, 7, 15),
      end: new Date(2021,7,14),
      name: " #2435644 (YD 1.200.000 TL - MD 1.200.000 TL) 1 Konut   ",
      id: "ekspertiz-2",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      styles: { progressColor: 'gray', progressSelectedColor: 'gray',backgroundColor: 'gray' },
      project: "ekspertiz",
      displayOrder: 11,
    },
    {
      start: new Date(2021, 3, 16),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: " #2735207 (YD 1.800.000 TL - MD 1.950.000 TL) 1 Konut   ",
      id: "ekspertiz-3",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "ekspertiz",
      displayOrder: 12,
    },
    {
      start: new Date(2017, 12, 4),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: "Ana Taşınmaz - 10 Katlı Betonarme Bina",
      id: "anaTasinmaz-sbi",
      progress: 100,
      styles: {hide:true},

      type: "project",
      hideChildren: true,
      displayOrder: 13,
    },
    {
      start: new Date(2016, 12, 4),
      end: new Date(2017,11,14),
      name: " Şerh: Tamamı Orman Sınırı İçinde   ",
      id: "anaTasinmaz-sbi-1",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      styles: { progressColor: 'gray', progressSelectedColor: 'gray',backgroundColor: 'gray' },
      project: "anaTasinmaz-sbi",
      displayOrder: 14,
    },
    {
      start: new Date(2015, 12, 3),
      end: new Date(2018,1,4),
      name: " Şerh: İmar Planında Turizm Tesis Alanı Belirtilmesi    ",
      id: "anaTasinmaz-sbi-3",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      styles: { progressColor: 'gray', progressSelectedColor: 'gray',backgroundColor: 'gray' },
      project: "anaTasinmaz-sbi",
      displayOrder: 15,
    },
    {
      start: new Date(2016, 12, 22),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: " Beyan: 6306 Sayılı Kanun Gereğince Riskli Yapı Beyanı    ",
      id: "anaTasinmaz-sbi-4",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "anaTasinmaz-sbi",
      displayOrder: 16,
    },
    {
      start: new Date(2017, 10, 10),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: "Bağımsız Bölüm - No:4",
      id: "bagimsizBolum-sbi",
      progress: 100,
      type: "project",
      styles: {hide:true},

      hideChildren: true,
      displayOrder: 17,
    },
    {
      start: new Date(2017, 10, 10),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: " Şerh: Kira Şerhi (01.01.2028'e kadar)    ",
      id: "bagimsizBolum-sbi-1",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "bagimsizBolum-sbi",
      displayOrder: 18,
    },
    {
      start: new Date(2016, 9, 9),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: " Beyan: Kat Mülkiyeti Çevirilmiştir Belirtmesi    ",
      id: "bagimsizBolum-sbi-2",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "bagimsizBolum-sbi",
      displayOrder: 19,
    },
    {
      start: new Date(2017, 10, 16),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: "Malikler",
      id: "Malikler",
      progress: 100,
      styles: {hide:true},

      type: "project",
      hideChildren: false,
      displayOrder: 20,
    },
    {
      start: new Date(2015, 10, 16),
      end: new Date(2016,3,23),
      name: "1. Ahmet Güneş (1/2) Hisse",
      id: "1.Hissedar",
      progress: 100,
      type: "project",

      project: "Malikler",
      hideChildren: true,
      styles: { progressColor: 'gray', progressSelectedColor: 'gray',backgroundColor: 'gray' },
      displayOrder: 21,
    },
    {
      start: new Date(2016, 10, 16),
      end: new Date(2017,3,21),
      name: " Mülkiyet Edinim Şekli: İntikal    ",
      id: "1.Hissedar-1",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "1.Hissedar",
      displayOrder: 22,
    },
    {
      start: new Date(2016, 7, 7),
      end: new Date(2017,1,9),
      name: " Şerh: İhtiyati Haciz   ",
      id: "1.Hissedar-2",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "1.Hissedar",
      displayOrder: 23,
    },
    {
      start: new Date(2016, 3, 17),
      end: new Date(2017,9,10),
      name: " Beyan: 5807 S.K. 4. Maddesine Göre Beyan    ",
      id: "1.Hissedar-3",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "1.Hissedar",
      displayOrder: 24,
    },
    {
      start: new Date(2017, 10, 16),
      end: new Date(2018,3,23),
      name: "2. Ayşenur Güneş (1/2) Hisse",
      id: "2.Hissedar",
      progress: 100,
      type: "project",
      project: "Malikler",
      hideChildren: true,
      styles: { progressColor: 'gray', progressSelectedColor: 'gray',backgroundColor: 'gray' },
      displayOrder: 25,
    },
    {
      start: new Date(2017, 10, 16),
      end: new Date(2018,3,21),
      name: " Mülkiyet Edinim Şekli: İntikal    ",
      id: "2.Hissedar-1",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "2.Hissedar",
      displayOrder: 26,
    },
    {
      start: new Date(2017, 2, 22),
      end: new Date(2018,3,16),
      name: " Şerh: İhtiyati Haciz   ",
      id: "2.Hissedar-2",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "2.Hissedar",
      displayOrder: 27,
    },
    {
      start: new Date(2017, 7, 12),
      end: new Date(2018,3,16),
      name: " Beyan: 5807 S.K. 4. Maddesine Göre Beyan    ",
      id: "2.Hissedar-3",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "2.Hissedar",
      displayOrder: 28,
    },
    {
      start: new Date(2018, 3, 16),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: "3. Cemil Merkant (1/1) Hisse",
      id: "3.Hissedar",
      progress: 100,
      type: "project",
      project: "Malikler",
      hideChildren: false,
      displayOrder: 29,
    },
    {
      start: new Date(2018, 3, 16),

      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()),
      name: " Mülkiyet Edinim Şekli: Satış    ",
      id: "3.Hissedar-1",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      project: "3.Hissedar",
      displayOrder: 30,
    },

  ];

  return tasks;
}

export function getStartEndDateForProject(tasks: Task[], projectId: string) {
  const projectTasks = tasks.filter(t => t.project === projectId);
  let start = projectTasks[0].start;
  let end = projectTasks[0].end;

  for (let i = 0; i < projectTasks.length; i++) {
    const task = projectTasks[i];
    if (start.getTime() > task.start.getTime()) {
      start = task.start;
    }
    if (end.getTime() < task.end.getTime()) {
      end = task.end;
    }
  }
  return [start, end];
}
